version: "3.3"

services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    networks:
      - new
    env_file:
      - app.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres?sslmode=disable
      SERVER_ADDRESS: 0.0.0.0:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: database
    image: postgres:13.3-alpine
    restart: always
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432" 
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
  migrate:
    container_name: migrate
    image: migrate/migrate
    networks:
      - new
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@database:5432/postgres?sslmode=disable", "up"]
    links: 
      - db
    depends_on:
      db:
        condition: service_healthy
networks:
      new: